name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      
    steps:
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          
          # FINAL FIX: We remove the theme and define all colors manually.
          # This sets the background and dots to be completely transparent.
          outputs: |
            dist/snake-dark.svg?color_snake=58a6ff&color_dots=#00000000&color_bg=#00000000

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
