name: Generate Snake Animation

on:
  schedule:
    # Runs every 12 hours
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # <-- This is the fix
      contents: write # <-- It gives the action permission to write
    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          # This line adds the magenta color to the snake
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=magenta
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=magenta

      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
